src/Entity/EpaperPageInterface.php
<?php

namespace Drupal\epaper\Entity;

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\RevisionLogInterface;
use Drupal\Core\Entity\EntityChangedInterface;
use Drupal\Core\Entity\EntityPublishedInterface;
use Drupal\user\EntityOwnerInterface;
use Drupal\user\UserInterface;

/**
 * Provides an interface for defining Page entities.
 *
 * @ingroup epaper
 */
interface EpaperPageInterface extends ContentEntityInterface, RevisionLogInterface, EntityChangedInterface, EntityPublishedInterface, EntityOwnerInterface {

  public function getImageUri(): ?string;

  public function getName(): string;

  public function setName(string $name): EpaperPageInterface;

  public function getCreatedTime(): int;

  public function setCreatedTime(int $timestamp): EpaperPageInterface;

  public function getRevisionCreationTime();

  public function setRevisionCreationTime($timestamp);

  public function getRevisionUser();

  public function setRevisionUserId($user_id);

  public function getIssue(): ?EpaperIssueInterface;

  public function getNumber(): ?int;

}

templates/rendered/epaper-app-container.html.twig
<!doctype html>
<html lang="{{ language }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }}</title>
  <meta name="description" content="None">
  <meta name="author" content="">
  <meta name="theme-color" content="{{ theme_color }}">

  <link rel="shortcut icon" type="image/png" href="{{ logo }}">

  <link rel="manifest" href="/app/manifest.json">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css" integrity="sha256-fx038NkLY4U1TCrBDiu5FWPEa9eiZu01EiLryshJbCo=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1/font/bootstrap-icons.min.css" integrity="sha256-BicZsQAhkGHIoR//IB2amPN5SrRb3fHB8tFsnqRAwnk=" crossorigin="anonymous">
  {% if calendar %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.3/dist/css/datepicker.min.css" integrity="sha256-Fcsjnn5m7b0jgoAOvto4YYPVkQb59WyWhygXflyYfwA=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.3/dist/css/datepicker-bs5.min.css" integrity="sha256-JI1ayAORlrsGdUc8e2SgChCZzhMPjvT2KOFfhZBay8Y=" crossorigin="anonymous">
  {% endif %}
  <link rel="stylesheet" href="{{ module_base_path }}/css/epaper.css">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js"></script>
  {% if calendar %}
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.3/dist/js/datepicker-full.min.js" integrity="sha256-94oRCk3emDMTwVIVqlAHLI22w+j/7l1TetC7JuddwhU=" crossorigin="anonymous"></script>
  {% endif %}
  <script type="module" src="{{ module_base_path }}/js/epaper.js"></script>
  {% if pwa %}
    <script>
      let pwaPath = '{{ module_base_path }}/js/serviceworker.js';
    </script>
    <script src="{{ module_base_path }}/js/pwa.js"></script>
  {% endif %}

</head>
<body>
  {{ content }}
</body>
</html>

templates/rendered/epaper-issue.html.twig
{% block header %}
  <nav class="navbar sticky-top navbar-expand-xl navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        {{ publication_icon }} {{ issue_name }}
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if regions is not empty %}
            <li class="nav-item dropdown my-2 my-xl-0 mx-xl-2 nav-item-editions">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="localIssuesMenuButton" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                Lokalausgaben
              </button>
              <div class="dropdown-menu mx-auto" aria-labelledby="localIssuesMenuButton">
                {% for region in regions %}
                  {{ region }}
                {% endfor %}
              </div>
            </li>
          {% endif %}
          <li class="nav-item my-2 my-xl-0 mx-xl-2 nav-item-pagination">
            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center">
                <li class="page-item {% if not last_issue_url %}disabled{% endif %}">
                  <a class="bi bi-caret-left-fill page-link date-last-navigation" href="{{ last_issue_url }}" aria-label="Previous"></a>
                </li>
                <li class="page-item">
                  <label class="d-none" for="datepicker">Datum</label>
                  <input
                    id="datepicker"
                    name="datepicker"
                    class="page-link"
                    type="date"
                    value="{{ issue_date }}"
                    min="2010-01-01"
                    max="{{ "now"|date("Y-m-d") }}"
                  >
                </li>
                <li class="page-item {% if not next_issue_url %}disabled{% endif %}">
                  <a class="bi bi-caret-right-fill page-link date-next-navigation" href="{{ next_issue_url }}" aria-label="Next"></a>
                </li>
              </ul>
            </nav>
          </li>
          {% if full_pdf_url is not empty %}
            <li class="nav-item nav-item-full-pdf">
              <a target="_blank" class="btn btn-primary my-2 my-xl-0 mx-xl-2" href="{{ full_pdf_url }}">
                <i class="bi bi-book-fill"></i>
                Gesamt-PDF
              </a>
            </li>
          {% endif %}
          {% if region_url is not empty %}
            <li class="nav-item nav-item-online">
              <a target="_blank" class="btn btn-secondary my-2 my-xl-0 mx-xl-2" href="{{ region_url }}">
                <i class="bi bi-globe"></i>
                Web
              </a>
            </li>
          {% endif %}
          <li class="nav-item nav-item-online">
            <button id="horizontalScrollToggle" type="button" class="btn btn-primary bi bi-distribute-horizontal" data-bs-toggle="button">Horizontal Scroll</button>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block main %}
<main class="edition-page">
  <h1 class="d-none d-xl-block">{{ epaper_issue.label() }}</h1>
  <div class="pages-container container-xl p-0 mx-xl-auto">
    {{ pages }}
  </div>
</main>
{% endblock %}

{% block modal %}
  {% include '@epaper/rendered/modal-element.html.twig' %}
{% endblock %}

{% block footer %}
<footer class="footer fixed-bottom dropup">
  <button
    class="btn btn-primary dropdown-toggle"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#pagePreviewContainer"
    aria-expanded="false"
    aria-controls="pagePreviewContainer"
    onclick="this.parentElement.classList.toggle('dropup')"
  >
    Vorschau
  </button>
  <div id="pagePreviewContainer" class="collapse bg-light">
    <div id="pagePreview" class="d-flex flex-nowrap align-items-end">
      {% set current_page_title = '' %}
      {% for page in pages_preview %}
        <a class="d-block py-1 px-3" href="#page-{{ page.number }}">
          {% if current_page_title != page.title %}
            {% set current_page_title = page.title %}
            <h5 class="small">{{ page.title }}</h5>
          {% endif %}
          {{ page.image }}
        </a>
      {% endfor %}
    </div>
  </div>
</footer>
{% endblock %}

templates/rendered/epaper-page.html.twig
{{ prefix }}
<div id="page-{{ page_number }}" {{ attributes.addClass('page-container') }}>
  <div class="card m-2">
    <div class="card-img-top page">
      <picture class="page-background">
        {% if page_image_webp %}<source srcset="{{ page_image_webp }}" type="image/webp">{% endif %}
        {% if page_image_jpg %}<source srcset="{{ page_image_jpg }}" type="image/jpeg">{% endif %}
        <img class="page" src="{{ page_image_jpg }}" loading="lazy" alt="{{ page.image.alt }}">
      </picture>
      {{ page_elements }}
    </div>
  </div>
</div>
{{ suffix }}

templates/rendered/epaper_element.html.twig
<a
  target="_blank"
  id="{{ element_id }}"
  title="{{ element_label }}"
  href="{{ element_url }}"
  class="element-placeholder"
  style="
    width:{{ element.bounds.width }}%;
    height:{{ element.bounds.height }}%;
    left:{{ element.bounds.left }}%;
    top:{{ element.bounds.top }}%;
  "
  data-top="{{ element.bounds.top }}"
  data-left="{{ element.bounds.left }}"
  data-width="{{ element.bounds.width }}"
  data-height="{{ element.bounds.height }}"
  data-name="{{ element_name }}"
  data-type="{{ element_type }}"
  {% if json_data is not empty %}
    data-json="{{ json_data }}"
  {% endif %}
  {% block additional_properties %}
  {% endblock %}
></a>

templates/rendered/modal-base-article.html.twig
{% set class = class ~ ' article-base' %}

{% extends '@epaper_theme/modal-element.html.twig' %}

{% block body %}

  <template class="gallery-image">
    <div class="carousel-item">
      <img class="d-block" src="" alt="#">
      <div class="text-center d-md-block">
        <p class="text-secondary">#</p>
      </div>
    </div>
  </template>

  <div class="text-start px-xl-5 px-md-4 px-2">
    <h5 class="article-title text-start py-2">Modal title</h5>
    <div class="hide-for-cutout">
      {% block article_head %}
        <div class="article-author text-secondary py-2"></div>
        <div class="article-preface font-weight-bolder py-2"></div>
      {% endblock %}
    </div>
    <div class="article-actions py-2 text-end">
      <a target="_blank" href="#" class="btn btn-primary print-trigger">
        <i class="bi bi-printer-fill"></i>
        <span class="d-none d-lg-inline">Drucken</span>
      </a>
      <button type="button" class="btn btn-primary my-1 cutout-trigger">
        <i class="bi bi-receipt"></i>
        <span class="d-none d-lg-inline">Ausschnitt</span>
      </button>
      <button type="button" class="btn btn-primary my-1 text-trigger">
        <i class="bi bi-text-center"></i>
        <span class="d-none d-lg-inline">Text</span>
      </button>
      <button type="button" id="text-to-speech-button" class="btn btn-primary my-1 speak">
        <i class="bi bi-volume-up-fill"></i>
        <span class="d-none d-lg-inline">Vorlesen</span>
      </button>
      <button type="button" class="btn btn-primary my-1 pause d-none">
        <i class="bi bi-pause-fill"></i>
        <span class="d-none d-lg-inline">Pausieren</span>
      </button>
      <div class="btn-group font-size-adjust" role="group" aria-label="Font size adjusts">
        <button type="button" class="btn btn-primary font-size-decrease">
          <i class="bi bi-dash-circle-fill"></i>
        </button>
        <button type="button" class="btn btn-primary font-size-default">
          <i class="bi bi-fonts"></i>
        </button>
        <button type="button" class="btn btn-primary font-size-increase">
          <i class="bi bi-plus-circle-fill"></i>
        </button>
      </div>
    </div>
    <div class="hide-for-cutout">
      {% block article_content %}

        <div class="article-images d-none carousel slide carousel-fade" data-bs-ride="false">
          <div class="carousel-inner">

          </div>
          <button type="button" class="carousel-control-prev" data-bs-target="#article-images" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Zurück</span>
          </button>
          <button type="button" class="carousel-control-next" data-bs-target="#article-images" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Weiter</span>
          </button>
        </div>

        <p class="article-text py-2"></p>

      {% endblock %}
    </div>
    <div class="cutout text-center px-1"><canvas></canvas></div>
  </div>
{% endblock %}

templates/rendered/modal-element.html.twig
<div
  class="modal fade {% if class %}{{ class }}{% endif %}"
  id="{% if id %}{{ id }}{% else %}elementModal{% endif %}"
  tabindex="-1"
  role="dialog"
  aria-labelledby="elementModal"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header d-flex justify-content-between">
        <div class="d-fill"></div>
        <h5 class="modal-title d-none font-weight-bold d-fill">Title</h5>
        <div class="modal-actions d-fill">
          <div class="btn-group flex-shrink-0 element-navigation my-1" role="group" aria-label="Article navigation">
            <button type="button" class="btn btn-primary my-1 last-article">
              <i class="bi bi-chevron-left"></i>
            </button>
            <button type="button" class="btn btn-primary my-1 next-article">
              <i class="bi bi-chevron-right"></i>
            </button>
          </div>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">
            <i class="bi bi-x"></i>
          </button>
        </div>
      </div>
      <div class="modal-body text-justify">
        {% block body %}
          <div class="cutout"><canvas></canvas></div>
        {% endblock %}
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Schließen</button>
      </div>
    </div>
  </div>
</div>